In [15]:
import pandas as pd

In [34]:
df1 = pd.read_csv(".\data\daily_sales_data_0.csv")
df2 = pd.read_csv(".\data\daily_sales_data_1.csv")
df3 = pd.read_csv(".\data\daily_sales_data_2.csv")

combined = pd.concat([df1, df2, df3], ignore_index=True)

combined.to_csv(".\data\combined.csv", index=False)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:3: SyntaxWarning: invalid escape sequence '\d'
<>:7: SyntaxWarning: invalid escape sequence '\d'
C:\Users\yadav\AppData\Local\Temp\ipykernel_44624\4027932846.py:1: SyntaxWarning: invalid escape sequence '\d'
  df1 = pd.read_csv(".\data\daily_sales_data_0.csv")
C:\Users\yadav\AppData\Local\Temp\ipykernel_44624\4027932846.py:2: SyntaxWarning: invalid escape sequence '\d'
  df2 = pd.read_csv(".\data\daily_sales_data_1.csv")
C:\Users\yadav\AppData\Local\Temp\ipykernel_44624\4027932846.py:3: SyntaxWarning: invalid escape sequence '\d'
  df3 = pd.read_csv(".\data\daily_sales_data_2.csv")
C:\Users\yadav\AppData\Local\Temp\ipykernel_44624\4027932846.py:7: SyntaxWarning: invalid escape sequence '\d'
  combined.to_csv(".\data\combined.csv", index=False)

In [35]:
combined.info()

<class 'pandas.DataFrame'>
RangeIndex: 41160 entries, 0 to 41159
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   41160 non-null  str
 1   price     41160 non-null  str
 2   quantity  41160 non-null  int64
 3   date      41160 non-null  str
 4   region    41160 non-null  str
dtypes: int64(1), str(4)
memory usage: 1.6 MB

In [36]:
combined_temp = combined.copy()

In [37]:
combined_temp["price"] = combined_temp["price"].replace(r"\$", "", regex=True).astype(float)

In [38]:
combined_temp["sales"] = combined_temp["price"] * combined_temp["quantity"]

In [39]:
combined_temp

                product  price  quantity        date region    sales
0           pink morsel   3.00       546  2018-02-06  north  1638.00
1           pink morsel   3.00       549  2018-02-06  south  1647.00
2           pink morsel   3.00       577  2018-02-06   east  1731.00
3           pink morsel   3.00       519  2018-02-06   west  1557.00
4           gold morsel   9.99       580  2018-02-06  north  5794.20
...                 ...    ...       ...         ...    ...      ...
41155  vermilion morsel   4.99       475  2022-02-14   west  2370.25
41156      lapis morsel   1.99       425  2022-02-14  north   845.75
41157      lapis morsel   1.99       454  2022-02-14  south   903.46
41158      lapis morsel   1.99       483  2022-02-14   east   961.17
41159      lapis morsel   1.99       427  2022-02-14   west   849.73

[41160 rows x 6 columns]

In [40]:
combined_temp = combined_temp[combined_temp["product"] == "pink morsel"]

In [42]:
combined_temp.drop("price", axis=1, inplace=True)
combined_temp.drop("product", axis=1, inplace=True)
combined_temp.drop("quantity", axis=1, inplace=True)

In [43]:
combined_temp

             date region   sales
0      2018-02-06  north  1638.0
1      2018-02-06  south  1647.0
2      2018-02-06   east  1731.0
3      2018-02-06   west  1557.0
28     2018-02-07  north  1587.0
...           ...    ...     ...
41107  2022-02-13   west  2390.0
41132  2022-02-14  north  2035.0
41133  2022-02-14  south  2465.0
41134  2022-02-14   east  2500.0
41135  2022-02-14   west  2115.0

[5880 rows x 3 columns]

In [44]:
combined_temp.to_csv(".\data\combined.csv", index=False)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\yadav\AppData\Local\Temp\ipykernel_44624\13715887.py:1: SyntaxWarning: invalid escape sequence '\d'
  combined_temp.to_csv(".\data\combined.csv", index=False)

In [1]:
x = [1, 2, 3]
y = x
y.append(4)
print(x)

[1, 2, 3, 4]